[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true

# OSX only
decorations = "None"

[window.padding]
x = 10
y = 10

[font]
size = 14.0

#[font.bold]
#family = "GeistMono Nerd Font"
#style = "Bold"
#
#[font.bold_italic]
#family = "GeistMono Nerd Font"
#style = "Bold Italic"
#
#[font.italic]
#family = "GeistMono Nerd Font"
#style = "Italic"

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

